name: make

on: push

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: make
      run: |
        make ARCH=haswell LDFLAGS='-static -s' SUFFIX=-linux
        echo "::set-output name=artifact::$(basename out/seawall-*)"
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.make.outputs.artifact }}
        path: out/seawall-*

  make-windows:
    runs-on: windows-latest
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        install: >-
          git
          base-devel
          mingw-w64-x86_64-gcc
    - uses: actions/checkout@v3
    - id: make
      shell: msys2 {0}
      run: |
        make ARCH=haswell LDFLAGS='-static -s' SUFFIX=-windows-mingw64
        echo "::set-output name=artifact::$(basename -s .exe out/seawall-*)"
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.make.outputs.artifact }}
        path: out/seawall-*
