name: make

on: push

jobs:
  make:
    strategy:
      matrix:
        platform:
        - runner: ubuntu-latest
          shell: 'bash {0}'
          suffix: -linux
        - runner: windows-latest
          shell: 'msys2 {0}'
          suffix: -windows-mingw64
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}
    runs-on: ${{ matrix.platform.runner }}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        install: >-
          git
          base-devel
          mingw-w64-x86_64-gcc
      if: ${{ matrix.platform.runner == 'windows-latest' }}
    - uses: actions/checkout@v3
    - id: make
      run: |
        make ARCH=haswell LDFLAGS='-static -s' SUFFIX=${{ matrix.platform.suffix }}
        echo "::set-output name=artifact::$(basename -s .exe out/seawall-*)"
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.make.outputs.artifact }}
        path: out/seawall-*
